import { Metadata } from "next";
import dynamic from "next/dynamic";

const AboutSectionOne = dynamic(
  () => import("@/components/About/AboutSectionOne"),
);
const AboutSectionTwo = dynamic(
  () => import("@/components/About/AboutSectionTwo"),
);
const Blog = dynamic(() => import("@/components/Blog"));
const Brands = dynamic(() => import("@/components/Brands"));
const Contact = dynamic(() => import("@/components/Contact"));
const Features = dynamic(() => import("@/components/Services"));
const Hero = dynamic(() => import("@/components/Hero"));
const Pricing = dynamic(() => import("@/components/Pricing"));
const Testimonials = dynamic(() => import("@/components/Testimonials"));
const Video = dynamic(() => import("@/components/Video"));
const ScrollUp = dynamic(() => import("@/components/Common/ScrollUp"));

const homeMetada = {
  url: "https://technosive.co.uk",
  title: "Technosive | Your Partner for Cybersecurity & Digital Protection",
  description:
    "Technosive: Your trusted partner in cybersecurity, providing comprehensive digital protection solutions to safeguard your business against evolving cyber threats.",
  imgUrl: "https://technosive.co.uk/images/logo/TechnosiveOG.webp",
  imgAltText: "Technosive Cybersecurity",
  keywords: [
    "Cybersecurity",
    "Digital Protection",
    "Technosive",
    "Threat Detection",
    "Risk Management",
    "Security Infrastructure",
    "Cyber Defense",
    "Data Protection",
    "Network Security",
    "Information Security",
    "Cyber Threats",
    "Security Solutions",
    "Vulnerability Assessment",
    "Penetration Testing",
    "Security Consulting",
    "Incident Response",
    "Compliance",
    "Security Audits",
    "Cybersecurity Services",
    "Digital Asset Protection",
    "Threat Intelligence",
    "Security Monitoring",
    "Cyber Risk Management",
    "Security Operations",
    "Cybersecurity Consulting",
    "Managed Security Services",
    "Security Awareness Training",
    "Cybersecurity Strategy",
    "Security Implementation",
    "Cyber Resilience",
    "Threat Prevention",
    "Security Assessment",
    "Cybersecurity Framework",
    "Security Governance",
    "Risk Assessment",
    "Security Architecture",
    "Cybersecurity Solutions",
    "Security Operations Center",
    "Incident Management",
    "Security Analytics",
    "Threat Hunting",
    "Security Automation",
    "Cybersecurity Expertise",
    "Security Best Practices",
    "Cybersecurity Standards",
    "Security Compliance",
    "Data Security",
    "Application Security",
    "Cloud Security",
    "Endpoint Security",
    "Identity and Access Management",
    "Security Awareness",
    "Cybersecurity Training",
    "Security Policies",
    "Risk Mitigation",
    "Security Strategy",
    "Cybersecurity Implementation",
    "Security Optimization",
    "Threat Response",
    "Security Monitoring",
    "Cybersecurity Management",
    "Security Operations",
    "Cybersecurity Services",
    "Security Solutions",
    "Digital Security",
    "Cyber Protection",
    "Security Consulting",
    "Cybersecurity Expertise",
    "Security Implementation",
    "Cybersecurity Strategy",
    "Security Management",
    "Cybersecurity Solutions",
    "Security Services",
    "Digital Protection",
    "Cyber Defense",
    "Security Infrastructure",
    "Threat Intelligence",
    "Security Analytics",
    "Cybersecurity Operations",
    "Security Monitoring",
    "Incident Response",
    "Security Assessment",
    "Cybersecurity Consulting",
    "Security Audits",
    "Compliance Management",
    "Risk Management",
    "Security Architecture",
    "Cybersecurity Framework",
    "Security Governance",
    "Security Policies",
    "Security Awareness",
    "Cybersecurity Training",
    "Security Best Practices",
    "Cybersecurity Standards",
    "Security Implementation",
    "Security Optimization",
    "Threat Prevention",
    "Security Response",
    "Cybersecurity Management",
    "Security Operations",
    "Cybersecurity Solutions",
    "Security Services",
    "Digital Security",
    "Cyber Protection",
    "Security Consulting",
    "Cybersecurity Expertise",
    "Security Implementation",
    "Cybersecurity Strategy",
    "Security Management",
    "Cybersecurity Solutions",
    "Security Services",
    "Digital Protection",
    "Cyber Defense",
    "Security Infrastructure",
    "Threat Intelligence",
    "Security Analytics",
    "Cybersecurity Operations",
    "Security Monitoring",
    "Incident Response",
    "Security Assessment",
    "Cybersecurity Consulting",
    "Security Audits",
    "Compliance Management",
    "Risk Management",
    "Security Architecture",
    "Cybersecurity Framework",
    "Security Governance",
    "Security Policies",
    "Security Awareness",
    "Cybersecurity Training",
    "Security Best Practices",
    "Cybersecurity Standards",
    "Security Implementation",
    "Security Optimization",
    "Threat Prevention",
    "Security Response",
    "Cybersecurity Management",
    "Security Operations",
    "Cybersecurity Solutions",
    "Security Services",
    "Digital Security",
    "Cyber Protection",
    "Security Consulting",
    "Cybersecurity Expertise",
    "Security Implementation",
    "Cybersecurity Strategy",
    "Security Management",
    "Cybersecurity Solutions",
    "Security Services",
    "Digital Protection",
    "Cyber Defense",
    "Security Infrastructure",
    "Threat Intelligence",
    "Security Analytics",
    "Cybersecurity Operations",
    "Security Monitoring",
    "Incident Response",
    "Security Assessment",
    "Cybersecurity Consulting",
    "Security Audits",
    "Compliance Management",
    "Risk Management",
    "Security Architecture",
    "Cybersecurity Framework",
    "Security Governance",
    "Security Policies",
    "Security Awareness",
    "Cybersecurity Training",
    "Security Best Practices",
    "Cybersecurity Standards",
  ],
};
const social = {
  title: homeMetada.title,
  description: homeMetada.description,
  images: [
    {
      url: homeMetada.imgUrl,
      alt: homeMetada.imgAltText,
    },
  ],
  url: homeMetada.url,
};
export const metadata: Metadata = {
  title: homeMetada.title,
  description: homeMetada.description,
  keywords: homeMetada.keywords,
  alternates: {
    canonical: homeMetada.url,
  },
  openGraph: social,
  twitter: social,
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function Home() {
  return (
    <main>
      <Hero />
      <Features />
      <Video />
      <AboutSectionOne />
      <AboutSectionTwo />
      <Brands />
      {/* <Testimonials /> */}
      {/* <Pricing /> */}
      <Blog />
      <Contact />
      <ScrollUp />
    </main>
  );
}
